Resources:
  Ec2Instance:
   Type: 'AWS::EC2::Instance'
   Properties:
     SecurityGroups:
       - !Ref InstanceSecurityGroup
     KeyName: deyaa-x1
     ImageId: 'ami-0194c3e07668a7e36' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
  InstanceSecurityGroup:
   Type: 'AWS::EC2::SecurityGroup'
   Properties:
     GroupDescription: Enable SSH access via port 22, http.server on port 3000
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: '22'
         ToPort: '22'
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: '3000'
         ToPort: '3000'
         CidrIp: 0.0.0.0/0
  