Parameters:
  EnvName:
    Type: String
    Default: circleci
  KeyName:
    Type: String

Resources:
  Ec2Instance:
   Type: 'AWS::EC2::Instance'
   Properties:
    InstanceType: t2.micro
    SecurityGroups:
      - !Ref InstanceSecurityGroup
    KeyName: !Sub ${KeyName}
    ImageId: 'ami-0194c3e07668a7e36' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
    Tags:
      - Key: Name
        Value: !Sub ${EnvName}-Instance
  InstanceSecurityGroup:
   Type: 'AWS::EC2::SecurityGroup'
   Properties:
     GroupDescription: Enable SSH access via port 22, http.server on port 3000, ping
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: '22'
         ToPort: '22'
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: '3000'
         ToPort: '3000'
         CidrIp: 0.0.0.0/0
       - IpProtocol: icmp
         FromPort: '8'
         ToPort: -1
         CidrIp: 0.0.0.0/0

