## configurations
version: 2.1

jobs:
  CF:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation create-stack --stack-name circle --template-body file://cf.yaml
      - run: aws cloudformation wait stack-create-complete --stack-name circle
      

workflows:
  awscircle:
    jobs:
      - CF

