## configurations
version: 2.1

jobs:
  CF:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation create-stack --stack-name circle --template-body file://cf.yaml
      - run: aws cloudformation wait stack-create-complete --stack-name circle
      - run: echo "[all]" > /tmp/ip
      - run: aws ec2 describe-instances --filters "Name=tag:Name,Values=circleci-Instance"  --output json --query "Reservations[*].Instances[*].{IP:PublicIpAddress}" | grep IP | cut -d '"' -f 4 >> /tmp/ip
      - persist_to_workspace:
          root: /tmp
          paths: ip
  CM:
    docker:
      - image: python:3.7-alpine3.11    
    steps:
      - attach_workspace:
        at: /tmp/ip
      - checkout
      - run: ansible-playbook -i /tmp/ip main.yml

workflows:
  awscircle:
    jobs:
      - CF

