## configurations
version: 2.1

jobs:
  CF:
    docker:
      - image: amazon/aws-cli
    environment:
      key: circleci
    steps:
      - checkout
      - run: aws ec2 create-key-pair --key-name ${key} --output text > /tmp/${key}.pem
      - run: aws cloudformation create-stack --stack-name circle --template-body file://cf.yaml --parameters ParameterKey=KeyName,ParameterValue=${key}
      - run: aws cloudformation wait stack-create-complete --stack-name circle
      - run: echo "[all]" > /tmp/ip
      - run: aws ec2 describe-instances --filters Name=instance-state-name,Values=[initializing|running] Name=tag:Name,Values=circleci-Instance  --query "Reservations[*].Instances[*].{IP:PublicIpAddress}" --output json | grep IP | cut -d '"' -f 4 >> /tmp/ip
      - save_cache:
          key: ip
          paths:
            - /tmp/
  CM:
    docker:
      - image: python:3.7-alpine3.11    
    steps:
      - restore_cache:
          keys:
            - ip
      - run: apk add ansible
      - checkout
      - run: ansible-playbook -i /tmp/ip main.yml --private-key /tmp/${key}.pem

workflows:
  awscircle:
    jobs:
      - CF
      - CM:
          requires:
            - CF

