---
- name: wait for server to be reachable
  wait_for_connection:
    delay: 10
    sleep: 10
    #connect_timeout: 3
    timeout: 300
  
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "index.js copy"
  copy:
    src: index.js
    dest: ~/udacity/index.js

- name: install npm
  become: yes
  apt:
    name: npm
    state: present

- name: install http server
  become: yes
  npm:
    name: http-server
    state: present

    #- name: "upgrade packages"
    #  become: yes
    #  yum:
    #    name: '*'
    #    state: latest
